import JSZip from "jszip";
import type { PeiDimension, PeiSection, PeiSlot, PeiStoryData } from "@/domain/PeiStory";
import type { ImportPreview } from "./ImportTypes";
const USER_ID = "00000000-0000-0000-0000-000000000001";
const labels: Record<string, PeiSection> = { summary: "summary", problem: "problem", action: "action", result: "result", reflection: "reflection" };
export class PeiImportService {
  async parseFile(file: File): Promise<ImportPreview<PeiStoryData>> { return file.name.toLowerCase().endsWith(".json") ? this.parseJson(await file.text()) : this.parseDocx(await file.arrayBuffer()); }
  private parseJson(text: string): ImportPreview<PeiStoryData> { try { const source = JSON.parse(text); if (!Array.isArray(source) && (!source || source.format !== "bench-pei" || source.version !== 1)) return this.failure("Choose a version 1 Bench PEI JSON backup."); const rows = Array.isArray(source) ? source : source.records; if (!Array.isArray(rows)) return this.failure("JSON backup must contain a records array."); return this.validate(rows.map((r: Partial<PeiStoryData>, i: number) => this.normalize(r, i)), "Bench PEI JSON"); } catch { return this.failure("The JSON file could not be read."); } }
  private async parseDocx(data: ArrayBuffer): Promise<ImportPreview<PeiStoryData>> { try { const zip = await JSZip.loadAsync(data); const xml = await zip.file("word/document.xml")?.async("string"); if (!xml) return this.failure("The DOCX is missing its document body."); const paragraphs = [...xml.matchAll(/<w:p\b[^>]*>[\s\S]*?<\/w:p>/g)].map(m => ({ xml: m[0], text: this.text(m[0]), style: m[0].match(/<w:pStyle[^>]*w:val="([^"]+)"/)?.[1] ?? "" })); const records: PeiStoryData[] = []; let bucket: PeiDimension | null = null; let story: Partial<PeiStoryData> & { current?: PeiSection } | null = null; const finish = () => { if (story && bucket) records.push(this.normalize({ ...story, dimension: bucket }, records.length)); story = null; }; for (const paragraph of paragraphs) { const t = paragraph.text.trim(); if (!t) continue; if (["Connection", "Drive", "Leadership", "Growth"].includes(t) && paragraph.style.toLowerCase().includes("heading")) { finish(); bucket = t.toLowerCase() as PeiDimension; continue; } if (bucket && paragraph.style.toLowerCase().includes("heading") && !labels[t.toLowerCase()]) { finish(); story = { title: t, dimension: bucket, slot: "main" }; continue; } if (!story) continue; if (t === "Main story" || t === "Backup story") { story.slot = t.startsWith("Main") ? "main" : "backup"; continue; } const section = Object.keys(labels).find(key => t.toLowerCase().startsWith(key)); if (section) { story.current = labels[section]; continue; } if (story.current) story[story.current] = story[story.current] ? `${story[story.current]}\n${t}` : t; } finish(); return this.validate(records, "McKinsey PEI DOCX"); } catch { return this.failure("The DOCX could not be read."); } }
  private normalize(row: Partial<PeiStoryData>, i: number): PeiStoryData { return { id: row.id ?? `imported-pei-${i + 1}`, userId: USER_ID, title: String(row.title ?? ""), dimension: row.dimension as PeiDimension, slot: row.slot as PeiSlot, summary: String(row.summary ?? ""), problem: String(row.problem ?? ""), action: String(row.action ?? ""), result: String(row.result ?? ""), reflection: String(row.reflection ?? ""), lastUsedOn: row.lastUsedOn ?? null, createdAt: row.createdAt ?? new Date().toISOString() }; }
  private validate(records: PeiStoryData[], format: string): ImportPreview<PeiStoryData> { const errors: { message: string; record?: string }[] = []; const validBuckets = ["connection", "drive", "leadership", "growth"]; const validSlots = ["main", "backup"]; const seen = new Set<string>(); records.forEach((r, i) => { const record = r.title || `Story ${i + 1}`; if (!r.title.trim()) errors.push({ record, message: "Title is required." }); if (!validBuckets.includes(r.dimension)) errors.push({ record, message: "Bucket must be Connection, Drive, Leadership, or Growth." }); if (!validSlots.includes(r.slot)) errors.push({ record, message: "Slot must be Main or Backup." }); for (const section of ["summary", "problem", "action", "result", "reflection"] as const) if (!r[section].trim()) errors.push({ record, message: `${section} is required.` }); const key = `${r.dimension}:${r.slot}`; if (seen.has(key)) errors.push({ record, message: "Each bucket can contain only one Main and one Backup story." }); seen.add(key); }); if (records.length !== 8) errors.push({ message: `Expected exactly 8 stories, found ${records.length}.` }); for (const bucket of validBuckets) for (const slot of validSlots) if (!seen.has(`${bucket}:${slot}`)) errors.push({ message: `Missing ${slot} story in ${bucket}.` }); return { format, version: 1, records, errors, warnings: [] }; }
  private failure(message: string): ImportPreview<PeiStoryData> { return { format: "Unknown", version: 1, records: [], errors: [{ message }], warnings: [] }; }
  private text(xml: string): string { return [...xml.matchAll(/<w:t(?:\s[^>]*)?>([\s\S]*?)<\/w:t>/g)].map(m => m[1]).join("").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"'); }
}
