"use client";
import Link from "next/link";
import { IconLink } from "@/components/ActionIcon";
import { useEffect, useMemo, useState } from "react";
import { SubTabs } from "@/components/nav/SubTabs";
import { networkTabs } from "@/components/nav/destinations";
import { getNetworkContactRepository, getApplicationRepository } from "@/repositories/factory";
import { useSession } from "@/lib/session/SessionContext";
import { useToday } from "@/lib/useToday";
import type { NetworkContact } from "@/domain/NetworkContact";
import type { Application } from "@/domain/Application";
import type { ContactImportRecord } from "@/repositories/NetworkContactRepository";
import { NetworkTransfer } from "@/components/network/NetworkTransfer";
import { JsonBackupService } from "@/services/JsonBackupService";

export default function NetworkPage() {
  const {userId}=useSession(), today=useToday();
  const [data,setData]=useState<{contacts:NetworkContact[];apps:Application[]}|null>(null);
  const [error,setError]=useState(false),[attempt,setAttempt]=useState(0);
  const [query,setQuery]=useState(""),[tag,setTag]=useState(""),[referral,setReferral]=useState(""),[sort,setSort]=useState("recent");
  useEffect(()=>{let active=true;Promise.all([getNetworkContactRepository().list(userId),getApplicationRepository().list(userId)]).then(([contacts,apps])=>{if(active){setData({contacts,apps});setError(false);}}).catch(()=>{if(active)setError(true);});return()=>{active=false;};},[userId,attempt]);
  const tags=useMemo(()=>[...new Set(data?.contacts.flatMap(c=>c.tags)??[])].sort(),[data]);
  const shown=useMemo(()=>{const q=query.toLowerCase().trim();return (data?.contacts??[]).filter(c=>(!q||`${c.name} ${c.company??""}`.toLowerCase().includes(q))&&(!tag||c.tags.includes(tag))&&(!referral||c.canRefer===referral)).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="company"?(a.company??"").localeCompare(b.company??"")||a.name.localeCompare(b.name):sort==="followup"?(a.nextFollowUpOn??"9999").localeCompare(b.nextFollowUpOn??"9999")||a.name.localeCompare(b.name):b.updatedAt.localeCompare(a.updatedAt));},[data,query,tag,referral,sort]);
  const field="min-h-tap min-w-0 rounded-card border border-hairline bg-surface px-3 text-base";
  return <div className="min-w-0 space-y-4 pb-24"><SubTabs items={networkTabs}/>
    <div className="relative flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">Network</h1><p className="mt-1 text-sm text-secondary">Your people, conversations, and next follow-ups.</p></div><div className="flex gap-2"><NetworkTransfer parse={file=>JsonBackupService.parse<ContactImportRecord>(file,"bench-network",userId)} preview={rows=>getNetworkContactRepository().previewImport(userId,rows)} commit={(plan,incoming)=>getNetworkContactRepository().importMerge(userId,plan,incoming)} exportRecords={()=>getNetworkContactRepository().exportRecords(userId)} onImported={()=>setAttempt(n=>n+1)} /><Link href="/network/new" className="flex min-h-tap items-center rounded-card bg-accent px-4 text-sm font-medium text-surface">Add contact</Link></div></div>
    <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><input aria-label="Search contacts by name or company" placeholder="Search name or company" value={query} onChange={e=>setQuery(e.target.value)} className={field}/><select aria-label="Filter by tag" value={tag} onChange={e=>setTag(e.target.value)} className={field}><option value="">All tags</option>{tags.map(t=><option key={t}>{t}</option>)}</select><select aria-label="Filter referral availability" value={referral} onChange={e=>setReferral(e.target.value)} className={field}><option value="">Any referral availability</option>{["Yes","Maybe","No"].map(r=><option key={r} value={r}>Can refer: {r}</option>)}</select><select aria-label="Sort contacts" value={sort} onChange={e=>setSort(e.target.value)} className={field}><option value="recent">Recently changed</option><option value="name">Name A–Z</option><option value="company">Company A–Z</option><option value="followup">Follow-up urgency</option></select></div>
    {error?<div role="alert"><p>Could not load Network.</p><button className="min-h-tap text-accent" onClick={()=>{setError(false);setAttempt(n=>n+1);}}>Try again</button></div>:!data?<p>Loading contacts…</p>:<><p role="status" className="text-xs text-secondary">Showing {shown.length} of {data.contacts.length} contacts</p>{!shown.length?<p className="rounded-card border border-hairline bg-surface p-card text-secondary">{data.contacts.length?"No contacts match these filters.":"No contacts yet. Add one or upload your Network JSON."}</p>:<div className="min-w-0 divide-y divide-hairline rounded-card border border-hairline bg-surface">{shown.map(c=>{const state=c.followUpState(today);const count=data.apps.filter(a=>a.contactIds.includes(c.id)).length;return <article key={c.id} className="network-row grid min-w-0 gap-x-4 gap-y-1 px-3 py-3 lg:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)_minmax(0,1fr)_132px] lg:items-center lg:px-4">
      <div className="min-w-0"><Link href={`/network/${c.id}`} className="block min-h-tap"><h2 className="break-words text-sm font-semibold text-ink">{c.name}</h2><p className="truncate text-xs leading-5 text-secondary" title={[c.role,c.company].filter(Boolean).join(" · ")}>{[c.role,c.company].filter(Boolean).join(" · ")}</p></Link>{c.notes&&<p className="truncate text-xs leading-5 text-secondary">{c.notes}</p>}</div>
      <div className="flex min-w-0 flex-wrap gap-1">{c.relationshipStrength!=null&&<span className="rounded-full bg-page px-2 py-0.5 text-xs">Connection {c.relationshipStrength}/5</span>}{c.canRefer&&<span className={`rounded-full px-2 py-0.5 text-xs ${c.canRefer==="Yes"?"bg-green-50 text-green-800":"bg-page text-secondary"}`}>Refer: {c.canRefer}</span>}{c.tags.slice(0,2).map(t=><span key={t} className="max-w-full truncate rounded-full bg-page px-2 py-0.5 text-xs text-secondary">{t}</span>)}{c.tags.length>2&&<Link href={`/network/${c.id}`} aria-label={`View all ${c.tags.length} tags for ${c.name}`} className="inline-flex min-h-tap items-center px-1 text-xs text-accent">+{c.tags.length-2}</Link>}</div>
      {state!=="none"?<Link href={`/network/${c.id}`} className="flex min-h-tap min-w-0 flex-col justify-center text-xs"><span className={state==='pending'?'text-secondary':'font-medium text-flag-text'}>{state==='due'?'Due today':state==='overdue'?'Overdue':'Pending'} · {c.nextFollowUpOn}</span><span className="truncate leading-5 text-secondary">{c.nextFollowUpNote||'Follow up'}</span></Link>:<span className="hidden text-xs text-secondary lg:block" aria-label="No follow-up scheduled">—</span>}
      <div className="flex items-center justify-between lg:flex-col lg:items-end"><div className="flex shrink-0">{c.phone&&<IconLink icon="phone" href={`tel:${c.phone.replace(/[^+0-9]/g,'')}`} label={`Call ${c.name}`}/>}{c.email&&<IconLink icon="email" href={`mailto:${c.email}`} label={`Email ${c.name}`}/>}{c.profileUrl&&<IconLink icon="linkedin" href={c.profileUrl} newTab label={`Open ${c.name}'s LinkedIn profile`}/>}</div>{count>0&&<Link href={`/network/${c.id}`} className="flex min-h-tap items-center text-xs text-secondary lg:-mt-1" aria-label={`${count} linked applications for ${c.name}`}>{count} {count===1?'application':'applications'}</Link>}</div>
    </article>})}</div>}</>}
  </div>;
}
