"use client";
import { IconButton } from "@/components/ActionIcon";
import { DeleteRecord } from "@/components/DeleteRecord";
import { useState } from 'react';
import { PeiProgress, type PeiProgressData, type PracticeEntry } from '@/domain/PeiProgress';
import { todayIsoDate } from '@/lib/date';
export function PracticePanel({progress,onSave}:{progress:PeiProgress;onSave:(row:PeiProgressData)=>Promise<void>}) {
  const [draft,setDraft]=useState<PracticeEntry|null>(null),[baseline,setBaseline]=useState<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function save(row:PeiProgressData) {setBusy(true);setError('');try{await onSave(row);setDraft(null);setBaseline(null);}catch(e){setError(e instanceof Error?e.message:'Could not save practice. Try again.');}finally{setBusy(false);}}
  return <section className="panel space-y-4" aria-label="PEI practice">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Practice · Level {progress.level}/5</h2><p className="mt-1 text-xs text-secondary">Your self-assessment · {progress.practices.length} practice sessions</p></div><button className="btn btn-primary" disabled={!!draft||baseline!==null} onClick={()=>{setError('');setDraft({id:crypto.randomUUID(),occurredOn:todayIsoDate(),level:progress.level,notes:'',createdAt:new Date().toISOString()});}}>Log practice</button></div>
    {draft&&<form className="space-y-3 border-t border-hairline pt-4" onSubmit={e=>{e.preventDefault();void save({...progress,practices:[...progress.practices.filter(p=>p.id!==draft.id),draft]});}}><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2"><label className="field-label">Practice date<input autoFocus className="field" required type="date" value={draft.occurredOn} max={todayIsoDate()} onChange={e=>setDraft({...draft,occurredOn:e.target.value})}/></label><label className="field-label">Level after practice<select className="field" value={draft.level} onChange={e=>setDraft({...draft,level:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>Level {n}</option>)}</select></label><label className="field-label sm:col-span-2">Notes (optional)<textarea className="field min-h-24" rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label></fieldset><div className="flex gap-2"><button disabled={busy} className="btn btn-primary">Save practice</button><button disabled={busy} type="button" className="btn" onClick={()=>{setDraft(null);setError('');}}>Cancel</button></div></form>}
    {baseline!==null?<form className="flex flex-wrap items-end gap-2" onSubmit={e=>{e.preventDefault();void save({...progress,baseline});}}><label className="field-label">Starting level<select autoFocus className="field" disabled={busy} value={baseline} onChange={e=>setBaseline(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><button disabled={busy} className="btn btn-primary">Save baseline</button><button disabled={busy} type="button" className="btn" onClick={()=>setBaseline(null)}>Cancel</button></form>:<div className="flex items-center gap-1 text-xs text-secondary">Starting level: {progress.baseline}<IconButton icon="edit" label="Edit starting level" disabled={!!draft||busy} onClick={()=>setBaseline(progress.baseline)}/></div>}
    {error&&<p role="alert" className="text-sm text-flag-text">{error}</p>}
    {!!progress.practices.length&&<details><summary className="min-h-tap cursor-pointer text-sm font-medium">Practice history ({progress.practices.length})</summary><div className="divide-y divide-hairline">{progress.history.map(p=><article key={p.id} className="py-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm">{p.occurredOn} · Level {p.level}</p><div className="flex gap-3"><IconButton icon="edit" label={`Edit practice on ${p.occurredOn}`} disabled={busy||!!draft||baseline!==null} onClick={()=>{setError('');setDraft({...p});}}/><DeleteRecord label={`practice on ${p.occurredOn}`} disabled={busy||!!draft||baseline!==null} description="Delete this practice entry? The current level will be recalculated from the remaining history." onDelete={()=>onSave({...progress,practices:progress.practices.filter(e=>e.id!==p.id)})}/></div></div>{p.notes&&<p className="whitespace-pre-wrap break-words text-sm text-secondary">{p.notes}</p>}</article>)}</div></details>}
  </section>;
}
