"use client";
import { useState } from 'react';
import type { CompletedStep } from '@/domain/Application';
import { IconButton } from "@/components/ActionIcon";
import { DeleteRecord } from '@/components/DeleteRecord';
export function CompletedHistory({steps,title,save}:{steps:CompletedStep[];title:string;save?:(steps:CompletedStep[])=>Promise<void>}) {
  const [draft,setDraft]=useState<CompletedStep|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  return <section className="panel"><h2 className="font-semibold">{title}</h2><ol className="mt-3 divide-y divide-hairline">{[...steps].sort((a,b)=>b.completedOn.localeCompare(a.completedOn)).map(step=><li key={step.id} className="py-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-medium">{step.description}</p><p className="mt-1 text-xs text-secondary">Done {step.completedOn} · Originally due {step.dueOn}</p></div>{save&&<div className="flex flex-wrap gap-2"><IconButton icon="edit" label={`Edit ${step.description}`} disabled={!!draft} onClick={()=>{setError('');setDraft({...step});}}/><DeleteRecord label={step.description} disabled={!!draft} description="Delete this completed entry? This does not change the active next step or application status." onDelete={()=>save(steps.filter(s=>s.id!==step.id))}/></div>}</div>{step.notes&&<p className="mt-2 whitespace-pre-wrap break-words text-sm text-secondary">{step.notes}</p>}
    {draft?.id===step.id&&<form className="mt-3 space-y-3" onSubmit={async e=>{e.preventDefault();if(!save)return;setBusy(true);setError('');try{await save(steps.map(s=>s.id===draft.id?draft:s));setDraft(null);}catch{setError('Could not save. Your draft is still here.');}finally{setBusy(false);}}}><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2"><label className="field-label sm:col-span-2">Description<input autoFocus className="field" required value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="field-label">Original due date<input className="field" required type="date" value={draft.dueOn} onChange={e=>setDraft({...draft,dueOn:e.target.value})}/></label><label className="field-label">Completion date<input className="field" required type="date" value={draft.completedOn} onChange={e=>setDraft({...draft,completedOn:e.target.value})}/></label><label className="field-label sm:col-span-2">Notes<textarea className="field" rows={3} value={draft.notes??''} onChange={e=>setDraft({...draft,notes:e.target.value||null})}/></label></fieldset>{error&&<p role="alert" className="text-sm text-flag-text">{error}</p>}<div className="flex gap-2"><button disabled={busy} className="btn btn-primary">Save entry</button><button disabled={busy} type="button" className="btn" onClick={()=>setDraft(null)}>Cancel</button></div></form>}
    </li>)}</ol></section>;
}
